### ISSUE TITLE
Console is logging: "API resolved without sending a response for..."

### ISSUE THREAD

**Issue by ajzeller** [kukicado/building-modern-app-with-nextjs-and-mongodb#1]
Many thanks for putting this tutorial together @kukicado , this was very helpful to get me up and running with MongoDB and Next.js. 

Your code is working for me, however each API call throws
`API resolved without sending a response for /api/daily, this may result in a stalled requests.` to the console similar to [issue 10439](https://github.com/zeit/next.js/issues/10439).

I was wondering if you are able to replicate this issue and if you had a fix?

**Comment by adocomplete** [comment]
HI @ajzeller, I do get the same issue. It has something to do with the way I'm handling the middleware. I will try it with the canary build of next as it might be a framework issue (since the code still runs as intended), but let me double check this and get back to you! :)

**Comment by nickavignone** [comment]
fixed here
[PR](https://github.com/kukicado/building-modern-app-with-nextjs-and-mongodb/pull/2)

**Comment by ajzeller** [comment]
Much appreciated @nickavignone!
